version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_USER=postgres
    restart: unless-stopped

  springbootapp:
    image: simple:latest
    build:
      context: ./
      dockerfile: DockerFile
    container_name: simplewebapp
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres
